name: json_locale_generator
description: A generation tool that builds a class to get your json locale paths from dart code
version: 1.2.0
homepage: https://github.com/ronw98/json_locale_generator
repository: https://github.com/ronw98/json_locale_generator
issue_tracker: https://github.com/ronw98/json_locale_generator/issues

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  args: '^2.0.0'
  build: ^3.0.0
  build_config: '>=1.0.0 <2.0.0'
  code_builder: ^4.10.1
  collection: ^1.18.0
  dart_style: ^3.0.1
  equatable: ^2.0.7
  glob: ^2.1.2
  path: '>=0.9.0 <2.0.0'
  pub_semver: ^2.1.5
  recase: '>=4.0.0 <5.0.0'
  yaml: ^3.1.3


dev_dependencies:
  lint: ^2.3.0
  test: any
